apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
  - path: dep-todo-db.yaml

configMapGenerator:
  - name: cm-todo-java-db
    literals:
      - timezone="Asia/Singapore"