apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-java-db
  labels:
    app: todo-java
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: bitnami/postgresql:15.4.0-debian-11-r54
          name: todo-java-db
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
