apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: dep-todo.yaml
  
configMapGenerator:
  - name: todo-configmap
    literals:
      - timezone="Asia/Singapore"
      - java_options="-Xms2G -Xms2G"
      - spring_active_profiles="prod"
      - datasource_url="jdbc:h2:mem:todo"
      - datasource_driver_classname="org.hibernate.dialect.H2Dialect"
