apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-java-db
  name: todo-db-svc
spec:
  ports:
  - name: psql-port
    port: 5432
    protocol: TCP
    targetPort: psql-port
  selector:
    matchLabels:
      name: todo-java-db