apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: dep-todo.yaml
  - path: secret.yaml
  
configMapGenerator:
  - name: cm-todo-java
    literals:
      - timezone="Asia/Singapore"
      - java_options="-Xms2G -Xms2G"
      - spring_active_profiles="sit"
      - datasource_url="jdbc:postgresql://todo-java-db-svc:5432/todo-java-sit-db"
      - datasource_driver_classname="org.postgresql.Driver"
      - theme="green-theme"