apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-java-db-dep
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-java-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-java-db
        app.kubernetes.io/name: todo-java-db
    spec:
      imagePullSecrets:
        - name: quay
      containers:
        - name: todo-java-db
          image: bitnami/postgresql:15.4.0-debian-11-r54
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: cm-todo-java-db
                  key: timezone
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: cm-todo-java-db
                  key: database-name
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: database-credentials
                  name: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-credentials
                  name: password
            - name: POSTGRESQL_TIMEZONE
              value: Asia/Singapore
            - name: POSTGRESQL_LOG_TIMEZONE
              value: Asia/Singapore
          ports:
            - containerPort: 5432
              name: psql-port
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          securityContext:
            runAsNonRoot: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
