apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: todo-java-service-monitor
  name: todo-java-service-monitor
spec:
  endpoints:  
  - interval: 15s
    targetPort: 8080
    scheme: http
    path: /management/prometheus
  selector:
    matchLabels:
      app: todo-java
  namespaceSelector:
    any: true