apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-java-db-svc
    app.kubernetes.io/instance: todo-java-db-svc
    app.kubernetes.io/name: todo-java
  name: todo-java-db-svc
spec:
  ports:
  - name: psql-port
    port: 5432
    protocol: TCP
    targetPort: psql-port
  selector:
    app.kubernetes.io/name: todo-java-db