apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-java-tasks
spec:
  destination:
    name: ''
    namespace: pipeline-todo
    server: https://kubernetes.default.svc
  source:
    path: pipeline/tasks
    repoURL: https://github.com/secangkirkopipanas/todo-java-infra/
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
