apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: todo-java-build-and-push
spec:
  params:
    - name: SOURCE_CODE_GIT_REPO
      type: string
      default: "https://github.com/secangkirkopipanas/todo-application.git"
      description: "Git repository of source code"
    - name: SOURCE_CODE_GIT_REF
      type: string
      default: develop
      description: "Git ref of source code repo"
    - name: INFRA_GIT_REPO
      type: string
      default: "https://github.com/secangkirkopipanas/todo-application-infra.git"
      description: "Git repository of infra code"
    - name: INFRA_GIT_REF
      type: string
      default: main
      description: "Git ref of infra code repo"
    - name: IMAGE
      type: string
      default: quay.io/rh_rh/todo-java
      description: "Image name for application"
    - name: GIT_COMMIT_ID
      type: string
      description: "Last Git commit ID"
  workspaces:
    - name: shared-workspace
      description: | 
        This workspace contains source code, so they can be read by the next task.
    - name: maven-local-repo
      description: | 
        This workspace contains all Maven dependencies used by the application.
    - name: infra-repo
      description: | 
        This workspace contains all infra manifests.
  tasks:
    - name: fetch-source
      params:
      - name: url
        value: $(params.SOURCE_CODE_GIT_REPO)
      - name: revision
        value: $(params.SOURCE_CODE_GIT_REF)
      - name: deleteExisting
        value: "true"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-workspace
    - name: build
      taskRef:
        name: maven
      runAfter:
        - fetch-source
      params:
        - name: OPENJDK_IMAGE
          value: registry.access.redhat.com/ubi9/openjdk-17:1.16
        - name: GOALS
          value: "clean package checkstyle:check"
        - name: SKIP_TESTS
          value: "true"          
        - name: MAVEN_OPTS
          value: ""
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-local-repo
          workspace: maven-local-repo
    - name: build-image-and-push
      taskRef:
        name: s2i-java
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-local-repo
          workspace: maven-local-repo
        - name: infra-repo
          workspace: infra-repo
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: GIT_COMMIT_ID
          value: $(params.GIT_COMMIT_ID)
        - name: TLSVERIFY
          value: "false"
        - name: VERSION
          value: latest