apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: todo
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  orphanedResources: {}
  sourceRepos:
    - '*'