apiVersion: apps/v1
kind: Deployment
namespace: todo-java-dev
metadata:
  name: todo-java-app
  labels:
    app: todo-java
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: todo-java-app
          imagePullPolicy: Always
          image: quay.io/rh_rh/todo-java:latest
