apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-java-app-dep
  labels:
    app.kubernetes.io/name: todo-java
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: todo-java-app
          imagePullPolicy: Always
          image: quay.io/rh_rh/todo-java:latest
